apiVersion: apps/v1
kind: Deployment
metadata:
  name: projekt-nepremicnine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projekt-nepremicnine
  template:
    metadata:
      labels:
        app: projekt-nepremicnine
    spec:
      containers:
      - name: projekt-nepremicnine
        image: kristofzupan/projekt-nepremicnine:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-uri-secret
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: projekt-nepremicnine
spec:
  type: LoadBalancer
  selector:
    app: projekt-nepremicnine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000