apiVersion: apps/v1
kind: Deployment
metadata:
  name: properties-service
  labels:
    app: properties-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: properties-service
  template:
    metadata:
      labels:
        app: properties-service
    spec:
      containers:
      - name: properties-service
        image: kristofzupan/projekt-nepremicnine-properties-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-uri-secret
              key: MONGO_URI
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: properties-service
spec:
  selector:
    app: properties-service
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP