apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nepremicnine-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/properties
        pathType: Prefix
        backend:
          service:
            name: properties-service
            port:
              number: 80
      - path: /api/images
        pathType: Prefix
        backend:
          service:
            name: image-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: kibana
            port:
              number: 80