apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nepremicnine-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/properties
        pathType: Prefix
        backend:
          service:
            name: properties-service
            port:
              number: 80