name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      -main

env:
  RESOURCE_GROUP: "projektNepremicnineResourceGroup"
  CLUSTER_NAME: "projektNepremicnineCluster"
  DEPLOYMENT_MANIFEST_PATH: |
    k8s/deployment.yaml
    k8s/service.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

  docker-build-and-push:
    needs: build
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/projekt-nepremicnine:latest
          secret-envs: |
            MONGO_URI: ${{ secrets.MONGO_URI }}

  #deploy:
  #  needs: docker-build-and-push
  #  runs-on: ubuntu-latest

  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4
  #    
  #    - name: Azure login
  #      uses: azure/login@v1.4.6
  #      with:
  #        client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #    # Step 3: Configure kubelogin for Azure auth
  #    - name: Set up kubelogin
  #      uses: azure/use-kubelogin@v1
  #      with:
  #        kubelogin-version: 'v0.0.25'

  #    # Step 4: Get AKS context
  #    - name: Get Kubernetes context
  #      uses: azure/aks-set-context@v3
  #      with:
  #        resource-group: ${{ env.RESOURCE_GROUP }}
  #        cluster-name: ${{ env.CLUSTER_NAME }}
  #        admin: 'false'
  #        use-kubelogin: 'true'

      # Step 5: Deploy application to AKS
  #    - name: Deploy to AKS
  #      uses: Azure/k8s-deploy@v4
  #      with:
  #        action: deploy
  #        manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
  #        images: |
  #          ${{ secrets.DOCKER_USERNAME }}/projekt-nepremicnine:latest
